[package]
name = "mouse-jiggler"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.48.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
tray-item = "0.6.0"
anyhow = "1.0"
